const config = {
    governanceAddress: "", // defaults to deployer
    mintAuthority: "", // RenVM public key
    mintFee: 25,
    burnFee: 10,

    // Overwritten by each network configuration.
    tokenPrefix: "mock",
    chainName: "Ethereum",
}

// mintAuthority is generated by
// > utils.toChecksumAddress(utils.pubToAddress("... public key ...", true).toString("hex"))

module.exports = {
    mainnet: {
        RenProxyAdmin: "0xDf1D8eD27C54bBE5833320cf5a19fd9E73530145",

        GatewayRegistry: "0xe80d347DF1209a76DD9d2319d62912ba98C54DDD",
        BasicAdapter: "0x32666B64e9fD0F44916E1378Efb2CFa3B3B96e80",

        RenERC20LogicV1: "0xe2d6cCAC3EE3A21AbF7BeDBE2E107FfC0C037e80",
        MintGatewayLogicV1: "0x402ec534BaF9e8Dd2968c57fDea368f3856460d6",

        assets: [
            { //  renBTC
                symbol: "BTC",
                decimals: 8,
                token: "0xEB4C2781e4ebA804CE9a9803C67d0893436bB27D",
                gateway: "0xe4b679400F0f267212D5D812B95f58C83243EE71",
            },
            { // renZEC
                symbol: "ZEC",
                decimals: 8,
                token: "0x1C5db575E2Ff833E46a2E9864C22F4B22E0B37C2",
                gateway: "0xc3BbD5aDb611dd74eCa6123F05B18acc886e122D",
            },
            { // renBCH
                symbol: "BCH",
                decimals: 8,
                token: "0x459086F2376525BdCebA5bDDA135e4E9d3FeF5bf",
                gateway: "0xCc4FF5b8A4A7adb35F00ff0CBf53784e07c3C52F",
            }
        ],

        config: {
            ...config,
            governanceAddress: "", // defaults to deployer
            feeRecipient: "0xE33417797d6b8Aec9171d0d6516E88002fbe23E7",
            mintAuthority: "0x7f64e4e4b2d7589eb0ac8439c0e639856aeceee7",

            tokenPrefix: "ren",
        },
    },

    testnet: {
        RenProxyAdmin: "0x4C695C4Aa6238f0A7092733180328c2E64C912C7",

        GatewayRegistry: "0x557e211EC5fc9a6737d2C6b7a1aDe3e0C11A8D5D",
        BasicAdapter: "0x7DDFA2e5435027f6e13Ca8Db2f32ebd5551158Bb",

        RenERC20LogicV1: "0xCe77c29b479bDF510f39bc4A2e43B0E4344fAB0f",
        MintGatewayLogicV1: "0x080d856994Fed1124c93AcA580aF035a86e9e9c7",

        assets: [
            { //  testBTC
                symbol: "BTC",
                decimals: 8,
                token: "0x0A9ADD98C076448CBcFAcf5E457DA12ddbEF4A8f",
                gateway: "0x55363c0dBf97Ff9C0e31dAfe0fC99d3e9ce50b8A",
            },
            { // testZEC
                symbol: "ZEC",
                decimals: 8,
                token: "0x42805DA220DF1f8a33C16B0DF9CE876B9d416610",
                gateway: "0xAACbB1e7bA99F2Ed6bd02eC96C2F9a52013Efe2d",
            },
            { // testBCH
                symbol: "BCH",
                decimals: 8,
                token: "0x618dC53e856b1A601119F2Fed5F1E873bCf7Bd6e",
                gateway: "0x9827c8a66a2259fd926E7Fd92EA8DF7ed1D813b1",
            }
        ],

        config: {
            ...config,
            governanceAddress: "", // defaults to deployer
            feeRecipient: "0x0EC73cCDCd8e643d909D0c4b663Eb1B2Fb0b1e1C",
            mintAuthority: "0x44Bb4eF43408072bC888Afd1a5986ba0Ce35Cb54",

            tokenPrefix: "test",
        },
    },

    mainnetVDot3: {
        RenProxyAdmin: "0xfC3Df9AD8665d584d26ba62ECf961B30fF09bfb5",

        GatewayRegistry: "0x503670EC851C55EC1aCFB5230192da921467a24e",
        BasicAdapter: "0xAe65b0f676313Fd715F29D07538d1dc8557f2b1A",

        RenERC20LogicV1: "0xa074139a4975318E7c011783031504D1C177F8cA",
        MintGatewayLogicV1: "0x4a144820A415bDfa0030937608743CAE1d392029",

        assets: [
            { // renFIL
                symbol: "FIL",
                decimals: 18,
                token: "0xD5147bc8e386d91Cc5DBE72099DAC6C9b99276F5",
                gateway: "0xED7D080AA1d2A4D468C615a5d481125Bb56BF1bf",
            },
            { // renDGB
                symbol: "DGB",
                decimals: 8,
                token: "0xe3Cb486f3f5C639e98cCBaF57d95369375687F80",
                gateway: "0x05387a10Bb3EF789b6C2a9CE2d6C21D5a8c6B1aA",
            },
            { // testDOGE
                symbol: "DOGE",
                decimals: 8,
                token: "0x3832d2F059E55934220881F831bE501D180671A7",
                gateway: "0x2362843745615368F4ef0A43D7502353649C0783",
            },
            { // renLUNA
                symbol: "LUNA",
                decimals: 6,
                token: "0x52d87F22192131636F93c5AB18d0127Ea52CB641",
                gateway: "0xD7D7Deab930B6d3f98b35A26a4c431630d5AB874",
            }
        ],

        config: {
            ...config,
            governanceAddress: "0x33024cfb7af11a7cb12ab0dedefc5dd5f430381f", // defaults to deployer
            feeRecipient: "0xE33417797d6b8Aec9171d0d6516E88002fbe23E7", // defaults to deployer
            mintAuthority: "0xfd2baaba0981ee5002c9322c1e46b3ef80d78b8d", // defaults to deployer

            tokenPrefix: "ren",
        },
    },

    devnetVDot3: {
        RenProxyAdmin: "0x967dfcB47448bdb4556501726c24b397B3156DD9",

        GatewayRegistry: "0x1CAD87e16b56815d6a0b4Cd91A6639eae86Fc53A",
        BasicAdapter: "0xC8DD18A151FafFCab1B822108e49b4aE3bFff477",

        RenERC20LogicV1: "0x203277eB2c67E4752dBDd6880cA412aa8196cD8c",
        MintGatewayLogicV1: "0xA1AaD74b3B23421ddC5689F16e10C8a7A308606d",

        assets: [
            { // testBTC
                symbol: "BTC",
                decimals: 8,
                token: "0xB116c1a20647D5d1dD662C2f2B10C0a4A6124794",
                gateway: "0xe44B74eAcaE53E0c73571913c444D04eC124caE1",
            },
            { // testZEC
                symbol: "ZEC",
                decimals: 8,
                token: "0x60d8baE3054ce46E114B6570f5dD57e097bCcF8b",
                gateway: "0x05Fc7018d1C21d5BaD7FfFc70dCeFfF171B535D6",
            },
            { // testBCH
                symbol: "BCH",
                decimals: 8,
                token: "0xdcfce7Ab726F621A904d18eB285e89ceDc5e4a3e",
                gateway: "0xf02bF64ccb827ABA448Df22689517D39B9f74126",
            },
            { // testDGB
                symbol: "DGB",
                decimals: 8,
                token: "0xa12EEc002bDF7e2c6d680F1b14a7FeB08B8d688F",
                gateway: "0x55523730d5Bbcd42B5A11E5Ad16B5388c4FC1642",
            },
            { // testDOGE
                symbol: "DOGE",
                decimals: 8,
                token: "0x5Eaaf23bB994D6a0f49211c40E3E918ac252272b",
                gateway: "0x7bB74975c2781Fe86657a0B60702a17E12828E10",
            },
            { // testBNB
                symbol: "BNB",
                decimals: 18,
                token: "0xA95896AdA87b4F33547260C07d7ba3E1d5014142",
                gateway: "0x96d90d1d8cA49F06793f92AD69dCf1fC6bDD0784",
            },
            { // testFIL
                symbol: "FIL",
                decimals: 18,
                token: "0x91682f624523B3B883eBA5C43db81A863B41578b",
                gateway: "0xAC377D952cBe122AAAB92086EFbE8D4217D280F8",
            },
            { // testLUNA
                symbol: "LUNA",
                decimals: 6,
                token: "0x7393E7508f74a272449F3137065C55d6d4B84e87",
                gateway: "0xe5569cc97012d174961D12A60442775EA6D2Af1A",
            }
        ],

        config: {
            ...config,
            governanceAddress: "", // defaults to deployer
            feeRecipient: "", // defaults to deployer
            mintAuthority: "0x0d72570ea72626bcd049f43ced062e1ce67e616d", // defaults to deployer

            tokenPrefix: "dev",
        },
    },

    testnetVDot3: {
        RenProxyAdmin: "0xC9401b34c8d5F2ff203D4221aebcc46A81b52fe3",

        GatewayRegistry: "0xcF9F36668ad5b28B336B248a67268AFcF1ECbdbF",
        BasicAdapter: "0x6fA045D176CE69Fdf9837242E8A72e81c2750E64",

        RenERC20LogicV1: "0x6916A93e7Ea8a8f0711AeA0bf31fB295AB0e3c3d",
        MintGatewayLogicV1: "0xF4144f3958dD74dAC359F3DCe9e1B55D7b291c4d",

        assets: [
            { // devBTC
                symbol: "BTC",
                decimals: 8,
                token: "0x48d7442B9BB36FEe26a81E1b634D1c4f75BAe4Ad",
                gateway: "0x1E1A6B5288a6c804aDE4E597Ed8df7064A1d961A",
            },
            { // devZEC
                symbol: "ZEC",
                decimals: 8,
                token: "0xB0b458DeEa6DC99E683B63dAc3a6Ee5Fc1B6f493",
                gateway: "0x0b001a3a329F868dc4EcD5089f027ac6f4108240",
            },
            { // devBCH
                symbol: "BCH",
                decimals: 8,
                token: "0xDD35d74c8EF6981Eb8b01F8F74358Cf667B20Abe",
                gateway: "0xb6eC7Ca09F23612894f8D681cE2Ff8c07BA45D40",
            },
            { // devDGB
                symbol: "DGB",
                decimals: 8,
                token: "0xA6ABf9562874fec05aEDDd9426757af9d89cEE89",
                gateway: "0x17D013fBf38187D97B64512E4999e8F062A7d777",
            },
            { // devDOGE
                symbol: "DOGE",
                decimals: 8,
                token: "0x40fC71314361CAE71Ce340851D37553FE478B9A3",
                gateway: "0xe6233D686eF2B346e98031af8b9e55831C57D74C",
            },
            { // devBNB
                symbol: "BNB",
                decimals: 18,
                token: "0x12640903Fc6aD421e610259e93280edB123FB54d",
                gateway: "0x39c268e728Fce3fDc75534c7641FdE2024445B49",
            },
            { // devFIL
                symbol: "FIL",
                decimals: 18,
                token: "0x5fF7E913Cd7504F965c16daBA7e335e0e3Ee5409",
                gateway: "0xaD38ED4AF98b2159cD8A399FAeF863690510b8B5",
            },
            { // devLUNA
                symbol: "LUNA",
                decimals: 6,
                token: "0x77F710CCc6190b398792dCcC1755c514a3B18E56",
                gateway: "0x8f5d51E75131838A463be28c0D4E24c578eA289f",
            }
        ],

        config: {
            ...config,
            governanceAddress: "", // defaults to deployer
            feeRecipient: "", // defaults to deployer
            mintAuthority: "0xbb8c61159153d8a6ffd555584d1ac77fd57feca7", // defaults to deployer

            tokenPrefix: "test",
        },
    },

    bscMainnetVDot3: {
        RenProxyAdmin: "0xbdf27a048ea859a20fef6b956eaeea4e80f2bdc7",

        GatewayRegistry: "0x21C482f153D0317fe85C60bE1F7fa079019fcEbD",
        BasicAdapter: "0xAC23817f7E9Ec7EB6B7889BDd2b50e04a44470c5",

        RenERC20LogicV1: "0x3799006a87FDE3CCFC7666B3E6553B03ED341c2F",
        MintGatewayLogicV1: "0x6b8bB175c092DE7d81860B18DB360B734A2598e0",

        assets: [
            { // renBTC
                symbol: "BTC",
                decimals: 8,
                token: "0xfCe146bF3146100cfe5dB4129cf6C82b0eF4Ad8c",
                gateway: "0x95De7b32e24B62c44A4C44521eFF4493f1d1fE13",
            },
            { // renZEC
                symbol: "ZEC",
                decimals: 8,
                token: "0x695FD30aF473F2960e81Dc9bA7cB67679d35EDb7",
                gateway: "0xfdecB67cE94A22C8e227D17938c3127EA1B47B4E",
            },
            { // renBCH
                symbol: "BCH",
                decimals: 8,
                token: "0xA164B067193bd119933e5C1e7877421FCE53D3E5",
                gateway: "0x3023DD075B0291Cd6aDc890A1EBDD6C400595E08",
            },
            { // renFIL
                symbol: "FIL",
                decimals: 18,
                token: "0xDBf31dF14B66535aF65AaC99C32e9eA844e14501",
                gateway: "0x05Cadbf3128BcB7f2b89F3dD55E5B0a036a49e20",
            },
            { // renDGB
                symbol: "DGB",
                decimals: 8,
                token: "0x31a0D1A199631D244761EEba67e8501296d2E383",
                gateway: "0x7986568375Af35B427f3f51389d73196967C356a",
            },
            { // testDOGE
                symbol: "DOGE",
                decimals: 8,
                token: "0xc3fEd6eB39178A541D274e6Fc748d48f0Ca01CC3",
                gateway: "0x06A2C5d79c66268610eEBBca10AFa17092860830",
            },
            { // renLUNA
                symbol: "LUNA",
                decimals: 6,
                token: "0xc4Ace9278e7E01755B670C0838c3106367639962",
                gateway: "0x4d59f628CB8e4670b779eAE22aF0c46DebC06695",
            }
        ],

        config: {
            ...config,
            governanceAddress: "", // defaults to deployer
            feeRecipient: "", // defaults to deployer
            mintAuthority: "0xfd2baaba0981ee5002c9322c1e46b3ef80d78b8d", // defaults to deployer

            tokenPrefix: "ren",
            chainName: "BinanceSmartChain",
        },
    },

    bscTestnetVDot3: {
        RenProxyAdmin: "0x07F10424272579865249809BE7EB211f314d8B79",

        GatewayRegistry: "0x87e83f957a2F3A2E5Fe16d5C6B22e38FD28bdc06",
        BasicAdapter: "0x105435a9b0f375B179e5e43A16228C04F01Fb2ee",

        RenERC20LogicV1: "0x29Aa535b65b9C9A08bEdEbA8F9398aAf4832F98b",
        MintGatewayLogicV1: "0x2011F921dA099687387E194C4DDf5D4413ac681A",

        assets: [
            { // testBTC
                symbol: "BTC",
                decimals: 8,
                token: "0xF4FAf1b22CEe0a024ad6b12Bb29EC0E13F5827c2",
                gateway: "0x8a4a68DB5Ad08C215c6078111BE8793843A53302",
            },
            { // testDOGE
                symbol: "DOGE",
                decimals: 8,
                token: "0x78ecF69F6d23861C6F8Ca75C39b3Dc5E7a7eE8c2",
                gateway: "0x0E1B161b33dE8E56B917f4735AfC26d5cf760c0C",
            },
            { // testETH
                symbol: "ETH",
                decimals: 18,
                token: "0xe9Ab97d707ad9A67bd01345233C3c179f42F9aD0",
                gateway: "0x43D828c81Ea229f5F4601D12C5EC00133bD17dE1",
            },
            {
                symbol: "ZEC",
                decimals: 8,
                gateway: "0x44d4ee551934cfC8aD7f9Ae20ce4bA58f7ed9D3C",
                token: "0x84e70956240B9cf02300d69c22cd2b28fe139789",
            },
            {
                symbol: "BCH",
                decimals: 8,
                gateway: "0x6FCa0Ef511F2Dad8B51e55E3eB8E4404AFD2Feb0",
                token: "0x2788b9D0A5d8802e4D18980C21dAc74277b8c58C",
            },
            {
                symbol: "DGB",
                decimals: 8,
                gateway: "0x8e95761fF55Ec16ffc1845273387E17d829F3026",
                token: "0x621e18A6cF77dB6a1F531B03BE29e218b7B8c04d",
            },
            {
                symbol: "FIL",
                decimals: 18,
                gateway: "0x4d0F77d0f57ba3282AcA0B408F64bAa11D43156c",
                token: "0x3ce3266Ab11b6C23ea50dF8a777198d6dedAd85f",
            },
            {
                symbol: "LUNA",
                decimals: 6,
                gateway: "0x671c7f6319d04999dE58aF32075C50061383240F",
                token: "0x6e5F9FB4f1C9d1C579f5FDdF79E85a66686cc7a1",
            }
        ],

        config: {
            ...config,
            governanceAddress: "", // defaults to deployer
            feeRecipient: "", // defaults to deployer
            mintAuthority: "0x0d72570ea72626bcd049f43ced062e1ce67e616d",

            tokenPrefix: "test",
            chainName: "BinanceSmartChain",
        },
    },

    bscDevnetVDot3: {
        RenProxyAdmin: "0xCf44D3C75D2E1790314A4cb400Ed6a6732959194",

        GatewayRegistry: "0x838F881876f53a772D2F8E2f8aa2e4a996431495",
        BasicAdapter: "0x7de1253A8da6620351ec477b38BdC6a55FCd0f85",

        RenERC20LogicV1: "0xD83c880037eabfe01cCF4B0E0e8464686CE23e70",
        MintGatewayLogicV1: "0x77Aa76F7fdC7B465d0C279f0515eF1Ed07F1eC95",

        assets: [
            { // devBTC
                symbol: "BTC",
                decimals: 8,
                token: "0x5eB4F537889eC3C7Ec397F1acB33c70D8C0ee438",
                gateway: "0x6003FD1C2d4eeDed7cb5E89923AB457d1DE5cE89",
            },
            { // devDOGE
                symbol: "DOGE",
                decimals: 8,
                token: "0xAF787a25241c69ae213A8Ee08a2518D858b32dBd",
                gateway: "0x7517FadFA7247ffe52d57c78780FfF0662a09936",
            },
            { // devETH
                symbol: "ETH",
                decimals: 18,
                token: "0xdE0316Db06e3AA5F3291850694543aEA928E72Ca",
                gateway: "0x18E12421fdD63220e2A0A34497724431b1a829f4",
            },
            { // devZEC
                symbol: "ZEC",
                decimals: 8,
                token: "0xD566bB681a231f5648D7cB0f09A89cb47fd09513",
                gateway: "0x00E094aff24746196Bf73491A4C276fa4db503b4",
            },
            { // devBCH
                symbol: "BCH",
                decimals: 8,
                token: "0xE980BC9e17094EB273c6b5A1139b3A30EcdF05e0",
                gateway: "0xBA7236b2fbe3F12Df15a0d5fcE57d891016822f8",
            },
            { // devDGB
                symbol: "DGB",
                decimals: 8,
                token: "0x8C0248Ab26FcD6868Cc5aaea954f0ce28F8E103f",
                gateway: "0xd5E7d585D471BaFF2060dAFeaf701ff89114e439",
            },
            { // devFIL
                symbol: "FIL",
                decimals: 18,
                token: "0xD43DaA686Ea5b20fACaD7945a0eA1187f412958f",
                gateway: "0x36C0B3C9531B558055c8237E730e4f618d238Cb7",
            },
            { // devLUNA
                symbol: "LUNA",
                decimals: 6,
                token: "0x2c82a39549858A0fF1a369D84695D983791d0786",
                gateway: "0x26f4F36A070190Ee4379241DD1463A420768EB4B",
            }
        ],

        config: {
            ...config,
            governanceAddress: "", // defaults to deployer
            feeRecipient: "", // defaults to deployer
            mintAuthority: "0xbb8c61159153d8a6ffd555584d1ac77fd57feca7",

            tokenPrefix: "dev",
            chainName: "BinanceSmartChain",
        },
    },

    celoTestnetVDot3: {
        RenProxyAdmin: "0xf1DA6f4A594553335EdeA6B1203a4B590c752E32",

        GatewayRegistry: "0xD881213F5ABF783d93220e6bD3Cc21706A8dc1fC",
        BasicAdapter: "0xD087b0540e172553c12DEEeCDEf3dFD21Ec02066",

        RenERC20LogicV1: "0xB5072BE373a120d81c728e908Ed0710968fC247f",
        MintGatewayLogicV1: "0x5e3c8B0F7229f1F1873267B6811465fEF73d53CA",

        assets: [
            { //  testBTC
                symbol: "BTC",
                decimals: 8,
                token: "0x07F10424272579865249809BE7EB211f314d8B79",
                gateway: "0x3645115A577Ea62b0E305Be4329Eb7816Ae056eA",
            },
            { // testZEC
                symbol: "ZEC",
                decimals: 8,
                token: "0xEF685D1D44EA983927D9F8D67F77894fAEC92FCF",
                gateway: "0xF9fAE250B8dda539B9AFfEb606C8e2631976413E",
            },
            { // testBCH
                symbol: "BCH",
                decimals: 8,
                token: "0x49fa7a3B9705Fa8DEb135B7bA64C2Ab00Ab915a1",
                gateway: "0xc735241F93F87D4DBEA499EE6e1d41Ec50e3D8cE",
            }
        ],

        config: {
            ...config,
            governanceAddress: "", // defaults to deployer
            feeRecipient: "", // defaults to deployer
            mintAuthority: "0x44Bb4eF43408072bC888Afd1a5986ba0Ce35Cb54",

            tokenPrefix: "test",
            chainName: "Celo",
        },
    },

    config,
}