/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface GatewayRegistryInterface extends ethers.utils.Interface {
  functions: {
    "_directTransferOwnership(address)": FunctionFragment;
    "blacklistRecoverableToken(address)": FunctionFragment;
    "claimOwnership()": FunctionFragment;
    "getGatewayBySymbol(string)": FunctionFragment;
    "getGatewayByToken(address)": FunctionFragment;
    "getGateways(address,uint256)": FunctionFragment;
    "getRenTokens(address,uint256)": FunctionFragment;
    "getTokenBySymbol(string)": FunctionFragment;
    "initialize(address)": FunctionFragment;
    "isOwner()": FunctionFragment;
    "owner()": FunctionFragment;
    "pendingOwner()": FunctionFragment;
    "recoverTokens(address)": FunctionFragment;
    "removeGateway(string)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "setGateway(string,address,address)": FunctionFragment;
    "symbolIsValid(string)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "updateGateway(address,address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "_directTransferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "blacklistRecoverableToken",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "claimOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getGatewayBySymbol",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getGatewayByToken",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getGateways",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRenTokens",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenBySymbol",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "initialize", values: [string]): string;
  encodeFunctionData(functionFragment: "isOwner", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "recoverTokens",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "removeGateway",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setGateway",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "symbolIsValid",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateGateway",
    values: [string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "_directTransferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "blacklistRecoverableToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGatewayBySymbol",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGatewayByToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGateways",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRenTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenBySymbol",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isOwner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recoverTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeGateway",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setGateway", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "symbolIsValid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateGateway",
    data: BytesLike
  ): Result;

  events: {
    "LogGatewayDeregistered(string,string,address,address)": EventFragment;
    "LogGatewayRegistered(string,string,address,address)": EventFragment;
    "LogGatewayUpdated(address,address,address)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "LogGatewayDeregistered"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogGatewayRegistered"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "LogGatewayUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export class GatewayRegistry extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: GatewayRegistryInterface;

  functions: {
    _directTransferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    blacklistRecoverableToken(
      _token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    claimOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getGatewayBySymbol(
      _tokenSymbol: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getGatewayByToken(
      _token: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getGateways(
      _start: string,
      _count: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    getRenTokens(
      _start: string,
      _count: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    getTokenBySymbol(
      _tokenSymbol: string,
      overrides?: CallOverrides
    ): Promise<[string]>;

    initialize(
      _nextOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    isOwner(overrides?: CallOverrides): Promise<[boolean]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    pendingOwner(overrides?: CallOverrides): Promise<[string]>;

    recoverTokens(
      _token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    removeGateway(
      _symbol: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setGateway(
      _symbol: string,
      _token: string,
      _gatewayContract: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    symbolIsValid(
      _tokenSymbol: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateGateway(
      _token: string,
      _newGatewayContract: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  _directTransferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  blacklistRecoverableToken(
    _token: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  claimOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getGatewayBySymbol(
    _tokenSymbol: string,
    overrides?: CallOverrides
  ): Promise<string>;

  getGatewayByToken(_token: string, overrides?: CallOverrides): Promise<string>;

  getGateways(
    _start: string,
    _count: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getRenTokens(
    _start: string,
    _count: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getTokenBySymbol(
    _tokenSymbol: string,
    overrides?: CallOverrides
  ): Promise<string>;

  initialize(
    _nextOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  isOwner(overrides?: CallOverrides): Promise<boolean>;

  owner(overrides?: CallOverrides): Promise<string>;

  pendingOwner(overrides?: CallOverrides): Promise<string>;

  recoverTokens(
    _token: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  removeGateway(
    _symbol: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setGateway(
    _symbol: string,
    _token: string,
    _gatewayContract: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  symbolIsValid(
    _tokenSymbol: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateGateway(
    _token: string,
    _newGatewayContract: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    _directTransferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    blacklistRecoverableToken(
      _token: string,
      overrides?: CallOverrides
    ): Promise<void>;

    claimOwnership(overrides?: CallOverrides): Promise<void>;

    getGatewayBySymbol(
      _tokenSymbol: string,
      overrides?: CallOverrides
    ): Promise<string>;

    getGatewayByToken(
      _token: string,
      overrides?: CallOverrides
    ): Promise<string>;

    getGateways(
      _start: string,
      _count: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getRenTokens(
      _start: string,
      _count: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getTokenBySymbol(
      _tokenSymbol: string,
      overrides?: CallOverrides
    ): Promise<string>;

    initialize(_nextOwner: string, overrides?: CallOverrides): Promise<void>;

    isOwner(overrides?: CallOverrides): Promise<boolean>;

    owner(overrides?: CallOverrides): Promise<string>;

    pendingOwner(overrides?: CallOverrides): Promise<string>;

    recoverTokens(_token: string, overrides?: CallOverrides): Promise<void>;

    removeGateway(_symbol: string, overrides?: CallOverrides): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    setGateway(
      _symbol: string,
      _token: string,
      _gatewayContract: string,
      overrides?: CallOverrides
    ): Promise<void>;

    symbolIsValid(
      _tokenSymbol: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateGateway(
      _token: string,
      _newGatewayContract: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    LogGatewayDeregistered(
      _symbol?: null,
      _indexedSymbol?: string | null,
      _token?: string | null,
      _gatewayContract?: string | null
    ): TypedEventFilter<
      [string, string, string, string],
      {
        _symbol: string;
        _indexedSymbol: string;
        _token: string;
        _gatewayContract: string;
      }
    >;

    LogGatewayRegistered(
      _symbol?: null,
      _indexedSymbol?: string | null,
      _token?: string | null,
      _gatewayContract?: string | null
    ): TypedEventFilter<
      [string, string, string, string],
      {
        _symbol: string;
        _indexedSymbol: string;
        _token: string;
        _gatewayContract: string;
      }
    >;

    LogGatewayUpdated(
      _token?: string | null,
      _currentGatewayContract?: string | null,
      _newGatewayContract?: string | null
    ): TypedEventFilter<
      [string, string, string],
      {
        _token: string;
        _currentGatewayContract: string;
        _newGatewayContract: string;
      }
    >;

    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;
  };

  estimateGas: {
    _directTransferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    blacklistRecoverableToken(
      _token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    claimOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getGatewayBySymbol(
      _tokenSymbol: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getGatewayByToken(
      _token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getGateways(
      _start: string,
      _count: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getRenTokens(
      _start: string,
      _count: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTokenBySymbol(
      _tokenSymbol: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      _nextOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    isOwner(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    pendingOwner(overrides?: CallOverrides): Promise<BigNumber>;

    recoverTokens(
      _token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    removeGateway(
      _symbol: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setGateway(
      _symbol: string,
      _token: string,
      _gatewayContract: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    symbolIsValid(
      _tokenSymbol: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateGateway(
      _token: string,
      _newGatewayContract: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    _directTransferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    blacklistRecoverableToken(
      _token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    claimOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getGatewayBySymbol(
      _tokenSymbol: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getGatewayByToken(
      _token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getGateways(
      _start: string,
      _count: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getRenTokens(
      _start: string,
      _count: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTokenBySymbol(
      _tokenSymbol: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      _nextOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    isOwner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pendingOwner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    recoverTokens(
      _token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    removeGateway(
      _symbol: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setGateway(
      _symbol: string,
      _token: string,
      _gatewayContract: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    symbolIsValid(
      _tokenSymbol: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateGateway(
      _token: string,
      _newGatewayContract: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
